name             'chef-wrapper-ntp'
maintainer       'Cobus Bernard'
maintainer_email 'me@cobus.io'
license          'MIT'
description      'Installs/Configures chef-wrapper-ntp'
long_description 'Installs/Configures chef-wrapper-ntp'
version          '0.1.0'

depends 'ntp', '~> 1.8.6'
depends 'apt', '~> 2.9.2'
